Repository conda/infrastructure, pull requests merged in 2023-05, with the labels that each got.

#752 Adding electric-souperman and marcoesters to CLA
  .clabot
Labels: cla-signed

#753 Add `sausagenoods` to contributor list
  .clabot
Labels: cla-signed

#757 Fix Broken Links on Synced Docs
  HOW_WE_USE_GITHUB.md
Labels: cla-signed, type::documentation, source::anaconda

#761 Update Stale Bot Timing
  .github/workflows/stale.yml
Labels: cla-signed, source::anaconda

#770 Fix formatting of `.github/globals.yml` to make our yaml formatters happy 😄
  .github/global.yml
Labels: cla-signed

#766 Adding entry for the slow solvers
  HOW_WE_USE_GITHUB.md
Labels: cla-signed
